version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install -r requirements/dev.txt
          name: Install Deps
      - python/save-cache
