version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test_windows:
    steps:
      - checkout
      - run:
          name: Install python deps
          command: pip install -r requirements/dev.txt
      - run:
          command: tox
      - store_artifacts:
          path: output

  test_linux:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tox
      - store_artifacts:
          path: output

workflows:
  test:
    jobs:
      - test_linux
      - test_windows