version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  linux:
    docker:
      - image: circleci/python:3.8

commands:
  tox:
    description: "Build and test with tox"
    parameters:
      windows:
        default: false
        type: boolean
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - when:
          condition: << parameters.windows >>
          steps:
            - run:
                name: Install Python deps in a venv
                command: |
                  python3 -m venv venv
                  venv\Scripts\Activate.ps1
                  pip install -r requirements/dev.txt
      - unless:
          condition: << parameters.windows >>
          steps:
            - run:
                name: Install Python deps in a venv
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements/dev.txt
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tox
      - store_artifacts:
          path: output

jobs:
  build_windows:
    executor: win/default
    steps:
      - tox:
        windows: true
  build_linux:
    executor: linux
    steps:
      - tox:
        windows: false

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      - build_windows